### PR TITLE
Snakes and Ladders Game

### PR DESCRIPTION
**Pull request by iamrahulmahato**
## Introduction
It is the classical Snakes and Ladders using python

### CODE REVIEW

**Comment by iamrahulmahato** [comment]
@TusharAMD facing some issue in not finding img can yoy help
error1

**Comment by TusharAMD** [comment]
What is location of Board.png? You have done ./img/ but I cannot see img folder

**Comment by iamrahulmahato** [comment]
@TusharAMD check out the first img
in 2nd time i tried to create a folder img till now that pr i haven't pushed

**Comment by TusharAMD** [comment]
image
Working file for me

**Comment by iamrahulmahato** [comment]
ok then

**Pull request merged**
