### PR TITLE
Love calculator 💘

### PR DESCRIPTION
**Pull request by Mrjoy832**
-  Issue Fixed: #189 
- It's a   **Love calculator 💘**, made using **Python**

https://user-images.githubusercontent.com/77873383/168852279-a3852ac0-0bce-4823-8732-4ef52c9f2f80.mp4

### CODE REVIEW

**Comment by Mrjoy832** [comment]
@TusharAMD Kindly check

**Comment by TusharAMD** [comment]
image
Even this one. I can't merge PR. Please check.

**Comment by Mrjoy832** [comment]
> image Even this one. I can't merge PR. Please check.

wait please

**Comment by Mrjoy832** [comment]
@TusharAMD also it's fixed

**Comment by Mrjoy832** [comment]
> @TusharAMD also it's fixed

@TusharAMD please merge

**Comment by TusharAMD** [comment]
Done 👍

**Pull request merged**
