### PR TITLE
Hey Life-Stimulation Game

### LINKED ISSUE #306: Hey Life!
Game of Life simulation in python

### PR DESCRIPTION
**Pull request by AnIkeT126**
Fixes #306

### CODE REVIEW

**Comment by TusharAMD** [comment]
https://github.com/Naufaldo/Testing_Python/blob/master/life.py

**Comment by AnIkeT126** [comment]
> https://github.com/Naufaldo/Testing_Python/blob/master/life.py

What exactly is plagiarised... It's a simple maths based fucntion so it will remain same only... The same code might be available on 10 other places....
If i look for the code of palindrome number, it will be same everywhere, so who copied???

**Comment by AnIkeT126** [comment]
> > https://github.com/Naufaldo/Testing_Python/blob/master/life.py
> 
> What exactly is plagiarised... It's a simple maths based fucntion so it will remain same only... The same code might be available on 10 other places.... If i look for the code of palindrome number, it will be same everywhere, so who copied??

**Comment by AnIkeT126** [comment]
> > https://github.com/Naufaldo/Testing_Python/blob/master/life.py
> 
> What exactly is plagiarised... It's a simple maths based fucntion so it will remain same only... The same code might be available on 10 other places.... If i look for the code of palindrome number, it will be same everywhere, so who copied??? Similarly for cannon game #350 and rock paper scissor #427 , these are just maths fucntions, how can you change them?? Just explain me this

> > https://github.com/Naufaldo/Testing_Python/blob/master/life.py
> 
> What exactly is plagiarised... It's a simple maths based fucntion so it will remain same only... The same code might be available on 10 other places.... If i look for the code of palindrome number, it will be same everywhere, so who copied??? Similarly for cannon game #350 and rock paper scissor #427 , these are just maths fucntions, how can you change them?? Just explain me this.

@TusharAMD please explain so how will the maths simple functions chnage, and how will the complaint justify the same code for palindrom number in 100 other places...
It does not have UI which can be different hence copied, just a simple maths fucntion.
2*2 will be 4 everywhere, so how did I exactly copy????

**Pull request merged**
