### PR TITLE
Watch Game

### LINKED ISSUE #424: Watch Game
A stopwatch like game in python

### PR DESCRIPTION
**Pull request by AnIkeT126**
Fixes #424

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@TusharAMD this PR was made before the announcement so please merge this one, also u have merged 7 after the announcement so please at least merge the ones yesterday

**Comment by TusharAMD** [comment]
Can you please attach screenshot for this one?

**Comment by AnIkeT126** [comment]
> 

image
 Differnt values can be given to alter it

**Comment by AnIkeT126** [comment]
> Can you please attach screenshot for this one?

image
 different values can be given to alter it

**Comment by AnIkeT126** [comment]
@TusharAMD this is the basic image of the start of the watch.

**Comment by TusharAMD** [comment]
https://dynamicparallax.wordpress.com/2015/11/04/stop-watch-game/

**Pull request closed without merging**
