### PR TITLE
2048 Game

### LINKED ISSUE #422: 2048 game
2048 game in python

### PR DESCRIPTION
**Pull request by AnIkeT126**
Fixes #422

### CODE REVIEW

**Comment by AnIkeT126** [comment]
@TusharAMD please merge this PR

**Comment by AnIkeT126** [comment]
@TusharAMD this PR was made before the announcement so please merge this one, also u have merged 7 after the announcement so please at least merge the ones yesterday

**Comment by TusharAMD** [comment]
The PRs that are merged after announcement are checked for plagiarism and was approved by team, so I was asked to merge them

**Comment by TusharAMD** [comment]
https://www.geeksforgeeks.org/2048-game-in-python/

**Pull request closed without merging**
