### PR TITLE
Rock Paper Scissor

### LINKED ISSUE #391: Rock Paper Scissors
Classic game of rock paper scissor in python

### PR DESCRIPTION
**Pull request by AnIkeT126**
Rock Paper Scissor  game in python

Fixes #391

### CODE REVIEW

**Comment by TusharAMD** [comment]
Original Source https://github.com/LuanRamalho/Pedra-Papel-Tesoura/blob/main/game.py

**Comment by AnIkeT126** [comment]
Similarly for cannon game #350 and life stimulation game , these are just maths fucntions, how can you change them??
Just explain me this.

**Comment by TusharAMD** [comment]
Ok tell me which part is NOT copied?
image
Even the lines of code are same.

**Comment by TusharAMD** [comment]
image

**Pull request merged**
